name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy server to Heroku
        uses: AkhileshNS/heroku-deploy@v3.4.6
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "notedown-server"
          heroku_email: "ravindusachintha53@gmail.com"
          appdir: server
        env:
          HD_POSTGRES_DB_HOST: ${{secrets.POSTGRES_DB_HOST}}
          HD_POSTGRES_DB_NAME: ${{secrets.POSTGRES_DB_NAME}}
          HD_POSTGRES_DB_USERNAME: ${{secrets.POSTGRES_DB_USERNAME}}
          HD_POSTGRES_DB_PASSWORD: ${{secrets.POSTGRES_DB_PASSWORD}}
          HD_HIBERNATE_DDL_AUTO: ${{secrets.HIBERNATE_DDL_AUTO}}
          HD_DATA_SEEDER_ENABLED: ${{secrets.DATA_SEEDER_ENABLED}}
          HD_SWAGGER_ENABLED: ${{secrets.SWAGGER_ENABLED}}
          HD_JPA_OPEN_IN_VIEW: ${{secrets.JPA_OPEN_IN_VIEW}}
          HD_JPA_SHOW_SQL: ${{secrets.JPA_SHOW_SQL}}
          HD_INCLUDE_STACKTRACE: ${{secrets.INCLUDE_STACKTRACE}}

      - name: Deploy client to Heroku
        uses: AkhileshNS/heroku-deploy@v3.4.6
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "notedown-client"
          heroku_email: "ravindusachintha53@gmail.com"
          appdir: client
