name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      POSTGRES_DB_HOST: ${{secrets.POSTGRES_DB_HOST}}
      POSTGRES_DB_NAME: ${{secrets.POSTGRES_DB_NAME}}
      POSTGRES_DB_USERNAME: ${{secrets.POSTGRES_DB_USERNAME}}
      POSTGRES_DB_PASSWORD: ${{secrets.POSTGRES_DB_PASSWORD}}
    steps:
      - uses: actions/checkout@v2

      - name: Deploy to Heroku
        uses: AkhileshNS/heroku-deploy@v3.4.6
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "notedown-server"
          heroku_email: "ravindusachintha53@gmail.com"
          appdir: server
